kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./authenticationconfiguration.yaml
    containerPath: /etc/kubernetes/authenticationconfiguration.yaml

  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        authentication-config: /etc/kubernetes/authenticationconfiguration.yaml

- role: worker
