########################################################
# The mock authorization server is a trivial Node.js API
########################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mockauthorizationserver
---
kind: Service
apiVersion: v1
metadata:
  name: mockauthorizationserver
spec:
  selector:
    app: mockauthorizationserver
  ports:
  - name: http
    protocol: "TCP"
    port: 8443
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mockauthorizationserver
  labels:
    app: mockauthorizationserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockauthorizationserver
  template:
    metadata:
      labels:
        app: mockauthorizationserver
    spec:
      serviceAccountName: mockauthorizationserver
      containers:
      - name: mockauthorizationserver
        image: mockauthorizationserver:1.0
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mockauthorizationserver-route
spec:
  parentRefs:
  - name: nginx-gateway
    namespace: nginx
  hostnames:
  - login.test.example
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: mockauthorizationserver
      kind: Service
      port: 8443
